
package gui;

import com.si.baseDatos.Crud;
import com.si.baseDatos.Sql2;
import com.si.baseDatos.Sql3;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Inventario extends javax.swing.JFrame {

   Crud crud;
   private int idSeleccionado;
   Alumnos examinarAlumno;
   
   DefaultTableModel Modelo ; 
   
    public Inventario() {
        initComponents();
        this.crud = new Crud();
         this.Modelo = new DefaultTableModel();
         this.mostrarInventario();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar libros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 12), new java.awt.Color(17, 152, 85))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 680, 30));

        jButton1.setForeground(new java.awt.Color(17, 152, 85));
        jButton1.setText("Buscar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, -1, 30));

        tblInventario.setForeground(new java.awt.Color(17, 152, 85));
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblInventario.setEnabled(false);
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1160, 290));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 1240, 430));

        jPanel3.setBackground(new java.awt.Color(17, 152, 85));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setForeground(new java.awt.Color(17, 152, 85));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 120, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 30));

        jLabel2.setBackground(new java.awt.Color(0, 51, 153));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 152, 85));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro.png"))); // NOI18N
        jLabel2.setText("BiblioNET");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 350, 90));

        btnGuardar.setBackground(new java.awt.Color(204, 255, 0));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.setOpaque(true);
        btnGuardar.setSelected(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, -1, -1));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 620, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        VentanaPrincipal newframe = new VentanaPrincipal();
       newframe.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        
//        tblInventario.setEnabled(true);
//        btnGuardar.setEnabled(true);
      
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void tblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMouseClicked
 
//        int fila = this.tblInventario.getSelectedRow();
//        
//        this.idSeleccionado = Integer.parseInt( this.tblInventario.getValueAt(fila, 0).toString() );
    }//GEN-LAST:event_tblInventarioMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
             tblInventario.setEnabled(true);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
       tblInventario.setEnabled(false);
       btnGuardar.setEnabled(false);
       
       
         if(tblInventario.getSelectedRow()==-1){   //condicion que valida si se selecciono un registro para actualizar
          
            JOptionPane.showMessageDialog(null, "Error no selecciono un registro");
            
            
      }else{
           
         ActualizarInventario actInv = new ActualizarInventario();
         actInv.setVisible(true);
         int fil = this.tblInventario.getSelectedRow();
         
          
          idSeleccionado = Integer.parseInt(this.tblInventario.getValueAt(fil, 0).toString());
          String stock = this. tblInventario.getValueAt(fil, 1).toString(); 
          String cantidad = this.tblInventario.getValueAt(fil, 2).toString();
          
           //int estado =Integer.parseInt(this.tblInventario.getValueAt(fil, 3).toString()) ;
           //actInv.Uestado.getSelectedItem();
           
          actInv.Ustock.setText(stock);
          actInv.Ucant.setText(cantidad);
          //actInv.Uestado.setSelectedIndex(estado);
          //actInv.Uestado.setText(estado);

   
         }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblInventario;
    // End of variables declaration//GEN-END:variables

private void mostrarInventario(){
    
    DefaultTableModel modelo = (DefaultTableModel) this.tblInventario.getModel();
    modelo.addColumn("ID");
    modelo.addColumn("Stock");
    modelo.addColumn("Cantidad Disponible");
    modelo.addColumn("Estado");
    modelo.addColumn("ID de libro");
    modelo.addColumn("ID de prestamo");
//    modelo.addColumn("Edad");
    
          
    try {
        ResultSet resultado = this.crud.seleccionar(Sql3.seleccionarInventario());
        
        while(resultado.next()){  //usar objeto resultado y el metodo next que permitira iterar entre todos los resultados
            
            Object [] alumnos = {  //objeto que se anexara al modelo
              
                    resultado.getInt(1)
                    ,resultado.getInt(2)
                    ,resultado.getInt(3)
                    ,resultado.getString(4)
                    ,resultado.getInt(5)
                    ,resultado.getInt(6)        
            };
            
            modelo.addRow(alumnos);
            
        }//cierra while
        
        this.tblInventario.setModel(modelo);
        
    } catch (SQLException e) {
        System.out.println("error " +e.getMessage());
    }
    
    
}// cierra metodo mostrarAlu







}
