

package gui;

import com.si.baseDatos.Conexion;
import com.si.usuario.Seguridad;
import com.si.usuario.Usuario;
import java.awt.image.BufferedImage;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {
    
     private BufferedImage blurredImage;
     Usuario usuario;
     Seguridad seguridad;

    
    public Login() {
        initComponents();
        this.setTitle("Login");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
         //https://github.com/DJ-Raven/swing-glassmorphism-icon/tree/main
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpLogin = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Password = new javax.swing.JPasswordField();
        btnLimpiar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(92, 179, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogin.setBackground(new java.awt.Color(161, 161, 161));
        jpLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jpLogin.setForeground(new java.awt.Color(0, 145, 60));
        jpLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpLogin.setOpaque(false);
        jpLogin.setRequestFocusEnabled(false);
        jpLogin.setLayout(null);

        txtUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 0, 0));
        txtUser.setBorder(null);
        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jpLogin.add(txtUser);
        txtUser.setBounds(150, 170, 200, 30);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 152, 85));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usu2.png"))); // NOI18N
        jpLogin.add(jLabel3);
        jLabel3.setBounds(90, 170, 40, 30);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 152, 85));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contra2.png"))); // NOI18N
        jpLogin.add(jLabel1);
        jLabel1.setBounds(90, 230, 50, 40);

        btnAceptar.setBackground(new java.awt.Color(17, 152, 85));
        btnAceptar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(204, 204, 204));
        btnAceptar.setText("Iniciar sesión");
        btnAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAceptar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnAceptarStateChanged(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jpLogin.add(btnAceptar);
        btnAceptar.setBounds(130, 300, 110, 30);

        btnRegistro.setBackground(new java.awt.Color(17, 152, 85));
        btnRegistro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(204, 204, 204));
        btnRegistro.setText("Registrarse");
        btnRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jpLogin.add(btnRegistro);
        btnRegistro.setBounds(200, 360, 110, 30);

        jLabel2.setBackground(new java.awt.Color(0, 51, 153));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 152, 85));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro.png"))); // NOI18N
        jLabel2.setText("BiblioNET");
        jpLogin.add(jLabel2);
        jLabel2.setBounds(40, 40, 350, 110);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jpLogin.add(jSeparator1);
        jSeparator1.setBounds(150, 207, 200, 3);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jpLogin.add(jSeparator2);
        jSeparator2.setBounds(150, 270, 200, 10);

        Password.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jpLogin.add(Password);
        Password.setBounds(150, 232, 200, 30);

        btnLimpiar.setBackground(new java.awt.Color(0, 255, 255));
        btnLimpiar.setForeground(new java.awt.Color(17, 152, 85));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jpLogin.add(btnLimpiar);
        btnLimpiar.setBounds(270, 300, 90, 30);

        jPanel1.add(jpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 430, 430));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblioteca.jpg"))); // NOI18N
        fondo.setOpaque(true);
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed

        RegistroUsuario registro = new RegistroUsuario();
        registro.setVisible(true);
        this.dispose();
        

    }//GEN-LAST:event_btnRegistroActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        
        if (evt.getSource() == btnLimpiar) {
            this.txtUser.setText("");
            this.Password.setText("");
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        if(evt.getSource() == btnAceptar){
            VentanaPrincipal newframe = new VentanaPrincipal();
            newframe.setVisible(true);
            this.dispose();
            
        }
        
//        
//         if (evt.getSource() == this.btnAceptar) {
//            this.usuario = new Usuario();
//
//            //Obtenemos los datos que han ingresado en el VLogin
//            String nombreUsuario = this.txtUser.getText();
//            char[] contrasenaChars = this.Password.getPassword();            
//            String contrasena = this.seguridad.getHashMD5(new String(contrasenaChars));            
//            this.usuario.setNombreUsuario(nombreUsuario);
//            this.usuario.setContrasenia(contrasena);     
//         }
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnAceptarStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarStateChanged

    

    
 
    public static void main(String[] args) throws SQLException {
        
        Conexion.iniciar();
        
        //evaluar la condicion
        
        if(Conexion.conexion==null){
            
//            Login login=new Login();
//            login.setVisible(false);
           
             JOptionPane.showMessageDialog(null,"No Conectando BD");
             System.exit(0);
          
           
        }else {
            
//            JOptionPane.showMessageDialog(null,"Conectando exitodsamente la BD");
            Login login = new Login();
            login.setVisible(true);
        }
        
        
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JPanel jpLogin;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables


} 





