
package conalep;

import com.si.baseDatos.Crud;
import com.si.baseDatos.Sql2;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;


public class Alumnos extends javax.swing.JFrame {

    Crud crud;
   private int idSeleccionado;
   Alumnos examinarAlumno;
   
   DefaultTableModel Modelo ; 
   
    public Alumnos() {
        initComponents();
        this.crud = new Crud();
         this.Modelo = new DefaultTableModel();
         this.mostrarAlumnos();
         this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContenedor = new javax.swing.JPanel();
        jpContenedor2 = new javax.swing.JPanel();
        txtBuscador = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btRegresar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jpContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpContenedor2.setBackground(new java.awt.Color(255, 255, 255));
        jpContenedor2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 12), new java.awt.Color(17, 152, 85))); // NOI18N
        jpContenedor2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorActionPerformed(evt);
            }
        });
        jpContenedor2.add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 650, 30));

        btnBuscar.setForeground(new java.awt.Color(17, 152, 85));
        btnBuscar.setText("Buscar");
        jpContenedor2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, -1, 30));

        tblAlumnos.setForeground(new java.awt.Color(17, 152, 85));
        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlumnos);

        jpContenedor2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 990, 220));

        jpContenedor.add(jpContenedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 1150, 420));

        jPanel3.setBackground(new java.awt.Color(17, 152, 85));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btRegresar.setForeground(new java.awt.Color(17, 152, 85));
        btRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        btRegresar.setText("Regresar");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });
        jPanel3.add(btRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 120, 30));

        jpContenedor.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        lbTitulo.setBackground(new java.awt.Color(0, 51, 153));
        lbTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(17, 152, 85));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro.png"))); // NOI18N
        lbTitulo.setText("BiblioNET");
        jpContenedor.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 350, 90));

        btnEliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(17, 152, 85));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        jpContenedor.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 640, -1, -1));

        jPanel4.setBackground(new java.awt.Color(17, 152, 85));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setForeground(new java.awt.Color(17, 152, 85));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        jButton4.setText("Regresar");
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 120, 30));

        jpContenedor.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        getContentPane().add(jpContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        // TODO add your handling code here:
        
        VentanaPrincipal newframe = new VentanaPrincipal();
        newframe.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btRegresarActionPerformed

    private void tblAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnosMouseClicked
        
        //int fila = this.tblAlumnos.getSelectedRow();
        
        //this.idSeleccionado = Integer.parseInt( this.tblAlumnos.getValueAt(fila, 0).toString() );
        
    }//GEN-LAST:event_tblAlumnosMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel jpContenedor2;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables

    
    private void mostrarAlumnos(){
    
    DefaultTableModel modelo = (DefaultTableModel) this.tblAlumnos.getModel();
    modelo.addColumn("ID");
    //modelo.addColumn("Matricula");
    modelo.addColumn("Nombre");
    modelo.addColumn("Apellidos");
    modelo.addColumn("Dirección");
    modelo.addColumn("Teléfono");
    modelo.addColumn("Edad");
    
          
    try {
        ResultSet resultado = this.crud.seleccionar(Sql2.seleccionarAlumnos());
        
        while(resultado.next()){  //usar objeto resultado y el metodo next que permitira iterar entre todos los resultados
            
            Object [] alumnos = {  //objeto que se anexara al modelo
              
                    resultado.getInt(1)
                    ,resultado.getString(2)
                    ,resultado.getString(3)
                    ,resultado.getString(4)
                    ,resultado.getString(5)
                    ,resultado.getInt(6)
                    //,resultado.getInt(7)        
            };
            
            modelo.addRow(alumnos);
            
        }//cierra while
        
        this.tblAlumnos.setModel(modelo);
        
    } catch (SQLException e) {
        System.out.println("error " +e.getMessage());
    }
    
    
}// cierra metodo mostrarAlumnos      




}
