

package conalep;


import com.jhlabs.image.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class Login extends javax.swing.JFrame {
    
     private BufferedImage blurredImage;

    /**
     * Creates new form conalepIn
     */
    public Login() {
        
      
        initComponents();
         applyBlur();
        componentes();
       
         this.setExtendedState(MAXIMIZED_BOTH);
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpLogin = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Password = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(92, 179, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogin.setBackground(new java.awt.Color(161, 161, 161));
        jpLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpLogin.setForeground(new java.awt.Color(0, 145, 60));
        jpLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpLogin.setOpaque(false);
        jpLogin.setRequestFocusEnabled(false);
        jpLogin.setLayout(null);

        txtUser.setForeground(new java.awt.Color(204, 204, 204));
        txtUser.setBorder(null);
        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jpLogin.add(txtUser);
        txtUser.setBounds(150, 170, 200, 30);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 152, 85));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usu2.png"))); // NOI18N
        jpLogin.add(jLabel3);
        jLabel3.setBounds(90, 170, 40, 30);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 152, 85));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contra2.png"))); // NOI18N
        jpLogin.add(jLabel1);
        jLabel1.setBounds(90, 230, 50, 40);

        jButton2.setBackground(new java.awt.Color(17, 152, 85));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Aceptar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpLogin.add(jButton2);
        jButton2.setBounds(200, 300, 70, 30);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Registrar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpLogin.add(jButton1);
        jButton1.setBounds(180, 360, 110, 30);

        jLabel2.setBackground(new java.awt.Color(0, 51, 153));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 152, 85));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro.png"))); // NOI18N
        jLabel2.setText("BiblioNET");
        jpLogin.add(jLabel2);
        jLabel2.setBounds(40, 40, 350, 110);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jpLogin.add(jSeparator1);
        jSeparator1.setBounds(150, 200, 200, 10);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jpLogin.add(jSeparator2);
        jSeparator2.setBounds(150, 260, 200, 10);

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jpLogin.add(Password);
        Password.setBounds(150, 232, 200, 30);

        jPanel1.add(jpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 430, 430));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/b.jpg"))); // NOI18N
        fondo.setOpaque(true);
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 1380, 770));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1380, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
 
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JPanel jpLogin;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

private void componentes(){
        jpLogin = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                applyBlur();
            }
        };
        jpLogin.setLayout(null); // Asegúrate de que el layout sea null para poder posicionar componentes libremente

       fondo = new JLabel(new ImageIcon(getClass().getResource("/img/biblioteca.jpg")));
        fondo.setBounds(0, 0, 480, 770);
        jpLogin.add(fondo);

        // Resto de la inicialización de componentes aquí...

        getContentPane().add(jpLogin);
        pack();
}
    

private void applyBlur() {
        BufferedImage bufferedImage = new BufferedImage(jpLogin.getWidth(), jpLogin.getHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = bufferedImage.createGraphics();

        // Pintar el JPanel en la imagen
        jpLogin.paint(g2d);
        g2d.dispose();

        // Aplicar el filtro de desenfoque a la imagen de fondo del JPanel
        GaussianFilter blur = new GaussianFilter(500f); // Cambia el valor de desenfoque según lo desees
        blurredImage = blur.filter(bufferedImage, null);

//         Establecer la imagen de fondo desenfocada como fondo del JPanel
        jpLogin.setOpaque(true);
        jpLogin.setBackground(new Color(0, 0, 0, 10)); // Establecer un fondo transparente
        
        jpLogin.setBorder(null);
        

        // Crear un JLabel para mostrar la imagen de fondo desenfocada
        fondo = new JLabel(new ImageIcon(blurredImage));
        fondo.setBounds(0, 0, jpLogin.getWidth(), jpLogin.getHeight());
        jpLogin.add(fondo);
    }





/*    
private BufferedImage getFondoPanel(){
 
    BufferedImage bufferedImage = new BufferedImage(jpLogin.getWidth(), jpLogin.getHeight(), BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2d = bufferedImage.createGraphics();
    jpLogin.paint(g2d);
    g2d.dispose();
    
   GaussianFilter blur = new GaussianFilter(5); // Cambia el valor de desenfoque según lo desees
    blurredImage = blur.filter(bufferedImage, null);
    
   
        jpLogin.setOpaque(false);
        jpLogin.setBackground(new Color(0, 0, 0, 0)); // Establecer un fondo transparente
        jpLogin.setBorder(null);
        jpLogin.setLayout(null); // Asegúrate de que el layout sea null para poder posicionar componentes libremente
        
        // Crear un JLabel para mostrar la imagen de fondo desenfocada
        fondo = new javax.swing.JLabel(new javax.swing.ImageIcon(blurredImage));
        fondo.setBounds(0, 0, jpLogin.getWidth(), jpLogin.getHeight());
        jpLogin.add(fondo);
    
    return bufferedImage;
}
*/

}


// 





